import {test,expect} from '@playwright/test';
const paths=['/','/cottages','/gallery','/about','/experience','/contact'];
test('all six pages load, have separate content, and images work',async({page})=>{
 const errors=[],failures=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(r.url())});
 for(const path of paths){await page.goto('http://127.0.0.1:5173'+path);await expect(page.locator('main h1')).toHaveCount(1);await expect(page.locator('#navigation a[aria-current="page"]')).toHaveAttribute('href',path);await expect(page.locator('footer')).toContainText('Unofficial redesign concept.');for(const img of await page.locator('main img').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate(i=>i.complete&&i.naturalWidth>0)).toBeTruthy();}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
 await page.goto('http://127.0.0.1:5173');await expect(page.locator('.hero-background img')).toHaveAttribute('src',/pool-aerial/);await expect(page.locator('.dedicated-gallery')).toHaveCount(0);await page.locator('#navigation').getByRole('link',{name:'Gallery',exact:true}).click();await expect(page).toHaveURL(/\/gallery$/);await expect(page.locator('.dedicated-gallery figure')).toHaveCount(12);await page.goBack();await expect(page).toHaveURL('http://127.0.0.1:5173/');expect(errors).toEqual([]);expect(failures).toEqual([]);
});
test('gallery categories and accessible photo viewer',async({page})=>{
 await page.goto('http://127.0.0.1:5173/gallery');await page.getByRole('button',{name:'The cottages',exact:true}).click();await expect(page.locator('.dedicated-gallery figure:visible')).toHaveCount(3);await page.locator('.dedicated-gallery button:visible').first().click();await expect(page.locator('#photo-dialog')).toBeVisible();await expect(page.locator('.lightbox-caption')).toContainText('01 / 03');await page.keyboard.press('ArrowRight');await expect(page.locator('.lightbox-caption')).toContainText('02 / 03');await page.keyboard.press('Escape');await expect(page.locator('#photo-dialog')).toBeHidden();await page.getByRole('button',{name:'All photographs'}).click();await expect(page.locator('.dedicated-gallery figure:visible')).toHaveCount(12);
});
test('cottages verified details, direct booking and demo contact form',async({page})=>{
 await page.goto('http://127.0.0.1:5173/cottages');await page.getByRole('button',{name:'Discover the cottages',exact:true}).click();await expect(page.locator('#dialog-copy')).toContainText('14 wooden cottages');await page.keyboard.press('Escape');for(const a of await page.getByRole('link',{name:'BOOK YOUR STAY'}).all())await expect(a).toHaveAttribute('href','https://book-directonline.com/properties/bajalocottagecanggudirect');
 await page.goto('http://127.0.0.1:5173/contact');const requests=[];page.on('request',r=>{if(r.method()==='POST')requests.push(r.url())});await page.getByLabel('Your name', {exact:true}).fill('Test Visitor');await page.getByLabel('Email address').fill('test@example.com');await page.getByLabel('Your message').fill('A demonstration request');await page.getByRole('button',{name:'PREVIEW YOUR REQUEST'}).click();await expect(page.locator('#form-status')).toContainText('your message has not been sent');expect(requests).toEqual([]);
});
test('mobile navigation and responsive widths for every page',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});for(const width of [320,390,768,1024]){await page.setViewportSize({width,height:844});for(const path of paths){await page.goto('http://127.0.0.1:5173'+path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${path} at ${width}px`).toBeTruthy();}}
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:5173');await page.getByRole('button',{name:/Menu/}).click();await page.locator('#navigation').getByRole('link',{name:'About',exact:true}).click();await expect(page).toHaveURL(/\/about$/);await expect(page.locator('#navigation')).toBeHidden();
});
