import {chromium} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
const out=process.argv[2]||'/workspace/previsualisation';const sectionsOut=path.join(out,'pages');fs.mkdirSync(sectionsOut,{recursive:true});for(const f of fs.readdirSync(sectionsOut))if(f.endsWith('.png'))fs.unlinkSync(path.join(sectionsOut,f));
const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const html=fs.readFileSync(path.join(out,'Bajalo-site-complet.html'),'utf8');const routes=['/','/cottages','/gallery','/about','/experience','/contact'];const slug=route=>route==='/'?'home':route.slice(1);let sectionNumber=0;
for(const [device,width,height] of [['ordinateur',1440,1000],['telephone',390,844]]){
 const p=await b.newPage({viewport:{width,height},reducedMotion:'reduce'});const errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(r.request().url()==='http://127.0.0.1:5173/private-preview')return r.fulfill({contentType:'text/html',body:html});remote.push(r.request().url());return r.abort();});await p.goto('http://127.0.0.1:5173/private-preview');
 for(const route of routes){if(route!=='/')await p.locator('#navigation').evaluate((e,r)=>e.querySelector(`[href="#${r}"]`).click(),route);await p.waitForFunction(r=>document.querySelector('#navigation a[aria-current="page"]')?.getAttribute('href')==='#'+r,route);await p.evaluate(()=>document.fonts.ready);for(const i of await p.locator('main img').all()){await i.scrollIntoViewIfNeeded();await i.evaluate(e=>e.decode());}await p.evaluate(()=>scrollTo(0,0));await p.locator('.download-toolbar').evaluate(e=>e.style.display='none');await p.screenshot({path:path.join(out,`Bajalo-${slug(route)}-${device}.png`),fullPage:true});if(device==='ordinateur'){await p.screenshot({path:path.join(out,`Apercu-${slug(route)}.png`)});for(const section of await p.locator('main>section,footer').all())await section.screenshot({path:path.join(sectionsOut,`${String(++sectionNumber).padStart(2,'0')}.png`)});}if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(route+' horizontal overflow');}
 if(device==='ordinateur'){await p.locator('.download-toolbar').evaluate(e=>e.style.display='');const waiting=p.waitForEvent('download');await p.getByRole('button',{name:'Télécharger pour envoyer'}).click();const d=await waiting;const copy=path.join(out,'Bajalo-copie-test.html');await d.saveAs(copy);if(fs.statSync(copy).size<1000000)throw Error('Download incomplete');const copied=fs.readFileSync(copy,'utf8');await p.unroute('**/*');await p.route('**/*',r=>r.request().url()==='http://127.0.0.1:5173/private-preview'?r.fulfill({contentType:'text/html',body:copied}):r.abort());await p.goto('http://127.0.0.1:5173/private-preview');await p.locator('#navigation').getByRole('link',{name:'Gallery',exact:true}).click();await p.locator('.dedicated-gallery button').first().click();if(!await p.locator('#photo-dialog').isVisible())throw Error('Offline lightbox broken');await p.keyboard.press('Escape');await p.locator('#navigation').getByRole('link',{name:'About',exact:true}).click();await p.locator('.about-story').waitFor();if(await p.locator('.about-story').count()!==1)throw Error('Offline about route broken');fs.unlinkSync(copy);}
 if(errors.length)throw Error(errors.join());if(remote.length)throw Error('Unexpected requests '+remote.join());console.log(device+': six pages privées, images et navigation vérifiées');await p.close();
}
await b.close();
