import '@fontsource/bodoni-moda/latin-500.css';
import '@fontsource/bodoni-moda/latin-600.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import './style.css';
const booking = 'https://book-directonline.com/properties/bajalocottagecanggudirect';
const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.3"/></svg>';
const pictures = {
 'garden-evening':'Wooden Bajalo cottages and a tropical garden walkway at dusk',
 'garden-path':'A lush garden path between Bajalo’s wooden cottages',
 'cottage':'A wooden Bajalo cottage surrounded by tropical greenery',
 'bedroom':'A Bajalo bedroom with a canopy bed and wooden walls',
 'outdoor-bath':'A stone bathtub in Bajalo’s open-air tropical bathroom',
 'cottage-interior':'A Bajalo cottage interior opening onto its terrace',
 'pool-garden':'Bajalo’s swimming pool with tropical gardens and sun loungers',
 'pool-evening':'Bajalo’s swimming pool and illuminated cottages in the evening',
 'pool-aerial':'An aerial view of Bajalo’s pool, gardens and wooden cottages',
 'bathroom':'Wooden details and a stone basin in a Bajalo bathroom',
 'door-detail':'A decorative room lock at Bajalo',
 'pool':'Bajalo’s swimming pool framed by palm trees and cottages'
};
const image = (file, cls='', eager=false) => `<img class="${cls}" src="/images/${file}-1280.webp" srcset="/images/${file}-640.webp 640w, /images/${file}-1280.webp 1280w, /images/${file}-1920.webp 1920w" sizes="${cls.includes('full') ? '100vw' : '(max-width: 700px) 90vw, 60vw'}" alt="${pictures[file]}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`;
const book = (cls='') => `<a class="pill ${cls}" href="${booking}" target="_blank" rel="noopener noreferrer">BOOK YOUR STAY ${arrow}</a>`;
const mark = `<svg class="brand-mark" viewBox="0 0 60 60" fill="none" aria-hidden="true"><path d="M30 48V19M30 26C23 9 10 14 15 25c3 7 10 9 15 8M30 26c7-17 20-12 15-1-3 7-10 9-15 8M30 36C16 23 8 34 16 41c4 4 10 3 14-1M30 36c14-13 22-2 14 5-4 4-10 3-14-1" stroke="currentColor" stroke-width="1.5"/><path d="M19 49h22" stroke="currentColor"/></svg>`;
const homeMarkup = `
<header class="site-header"><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span>＋</span></button><nav id="navigation" aria-label="Main navigation"><a href="#home">Home</a><a href="#cottages">Cottages</a><a href="#gallery">Gallery</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a class="crest" href="#home" aria-label="Bajalo home">${mark}<span>B</span></a>${book('header-book')}</header>
<main>
<section class="hero" id="home"><div class="hero-background">${image('pool-aerial','full-image',true)}</div><div class="hero-topline"><span>BAJALO COTTAGE CANGGU</span><span>BALI, INDONESIA</span></div><div class="hero-bottom"><div class="hero-title"><p class="eyebrow">A BOUTIQUE ESCAPE IN BALI</p><h1>BAJALO<br><span>CANGGU</span></h1><a class="diamond" href="#introduction" aria-label="Discover Bajalo"><span>↓</span></a></div><a class="hero-postcard" href="#cottages">${image('bedroom','',true)}<span>YOUR LITTLE HIDEAWAY ${arrow}</span></a></div><div class="hero-baseline"><p>A peaceful hideaway in the heart of Canggu.</p><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="introduction" id="introduction"><div class="section-kicker"><span>01 / WELCOME TO BAJALO</span><span>WOODEN COTTAGES · TROPICAL GARDENS · BALI</span></div><div class="intro-grid"><h2>A little closer<br>to <em>nature.</em></h2><div class="intro-copy"><p class="statement">Fourteen wooden cottages.<br>A tropical setting.<br>Your own corner of Canggu.</p><p>Bajalo Cottage Canggu is a place to get away, settle in, and enjoy a different rhythm. An adults-only property, with wooden cottages designed for comfort and time to unwind.</p><a class="underlined" href="#cottages">EXPLORE THE COTTAGES ${arrow}</a></div></div><div class="intro-strip"><span>14 WOODEN COTTAGES</span><span>ADULTS-ONLY RETREAT</span><span>CANGGU, BALI</span></div></section>
<section class="cottages" id="cottages"><div class="section-kicker"><span>02 / YOUR STAY</span><span>COMFORT, IN THE DETAILS</span></div><div class="section-heading"><h2>Stay a<br><em>little longer.</em></h2><p>A cottage of your own.<br>Everything you need to feel at ease.</p></div><div class="stay-grid"><button class="stay-card" data-cottage="0" aria-label="Discover the cottages">${image('cottage')}<span class="stay-number">01</span><span class="stay-name">Wooden cottages ${arrow}</span></button><button class="stay-card" data-cottage="1" aria-label="Discover the bedrooms">${image('bedroom')}<span class="stay-number">02</span><span class="stay-name">Slow mornings ${arrow}</span></button><button class="stay-card" data-cottage="2" aria-label="Discover the open-air bathrooms">${image('outdoor-bath')}<span class="stay-number">03</span><span class="stay-name">Open-air bathing ${arrow}</span></button></div><div class="stay-description"><p>Each cottage features a comfortable bed, a working desk, a mini fridge and air conditioning. Step onto your terrace, with its own chair and table, or unwind in an open-air bathroom with a bathtub.</p>${book('outline')}</div></section>
<section class="gallery" id="gallery"><div class="section-kicker"><span>03 / THROUGH OUR LENS</span><span>REAL MOMENTS AT BAJALO</span></div><div class="gallery-collage"><h2>Gal<span>lery</span></h2><button class="gallery-piece piece-a" data-photo="garden-path" aria-label="Enlarge garden photograph">${image('garden-path')}</button><button class="gallery-piece piece-b" data-photo="pool-aerial" aria-label="Enlarge pool aerial photograph">${image('pool-aerial')}</button><button class="gallery-piece piece-c" data-photo="bedroom" aria-label="Enlarge bedroom photograph">${image('bedroom')}</button><button class="gallery-piece piece-d" data-photo="outdoor-bath" aria-label="Enlarge open-air bathroom photograph">${image('outdoor-bath')}</button><button class="gallery-piece piece-e" data-photo="door-detail" aria-label="Enlarge cottage detail photograph">${image('door-detail')}</button><button class="gallery-piece piece-f" data-photo="cottage-interior" aria-label="Enlarge terrace photograph">${image('cottage-interior')}</button><p>Wood, water, light.<br>A few of our favourite things.</p></div><div class="photo-ribbon"><button data-photo="pool-evening" aria-label="Enlarge pool at dusk photograph">${image('pool-evening')}</button><button data-photo="bathroom" aria-label="Enlarge bathroom details photograph">${image('bathroom')}</button><button data-photo="cottage" aria-label="Enlarge wooden cottage photograph">${image('cottage')}</button><button data-photo="pool-garden" aria-label="Enlarge pool garden photograph">${image('pool-garden')}</button></div><p class="gallery-caption">A glimpse of Bajalo, in the property’s own photographs. <span>SELECT AN IMAGE TO TAKE A CLOSER LOOK ${arrow}</span></p></section>
<section class="experience" id="experience"><div class="experience-background">${image('garden-path','full-image')}</div><div class="experience-content"><p class="eyebrow">04 / THE BAJALO EXPERIENCE</p><h2>Your stay,<br><em>naturally.</em></h2><div class="amenity-cards"><article><span class="amenity-icon">01 / OUTDOOR LIVING</span><h3>A terrace<br>of your own.</h3><p>Each cottage has a terrace with a chair and table. A little space to sit back and unwind.</p></article><article><span class="amenity-icon">02 / OPEN-AIR BATHING</span><h3>Under<br>an open sky.</h3><p>An open-air bathroom with a bathtub, included in every cottage.</p></article><article><span class="amenity-icon">03 / SIMPLE COMFORTS</span><h3>Settle<br>right in.</h3><p>A comfortable bed, air conditioning, a mini fridge and a working desk.</p></article></div><div class="experience-caption"><span>AN ADULTS-ONLY PROPERTY</span><span>TAKE YOUR TIME. YOU’RE IN BALI.</span></div></div></section>
<section class="pool" id="pool"><div class="pool-heading"><p class="eyebrow">05 / BY THE WATER</p><h2>A slower<br>kind of <em>day.</em></h2><p>The pool, the gardens, and a little time for yourself.</p></div><div class="pool-wide">${image('pool','full-image')}<span>THE SIMPLE PLEASURE OF BEING HERE.</span></div></section>
<section class="location" id="location"><div class="section-kicker"><span>06 / FIND YOUR RHYTHM</span><span>CANGGU, BALI</span></div><div class="location-grid"><div class="location-image">${image('cottage-interior')}</div><div class="location-copy"><p class="eyebrow">YOUR CORNER OF THE ISLAND</p><h2>Here,<br>in <em>Canggu.</em></h2><p>Our wooden cottages are a base for your Bali escape. Bajalo’s website describes the centre of Canggu and the beach as a five-minute scooter ride away.</p><small>Travel time as stated by the hotel; conditions may vary.</small><a class="underlined" href="https://bajalocanggu.wixsite.com/bajalocanggu" target="_blank" rel="noopener noreferrer">DISCOVER BAJALO ${arrow}</a></div></div></section>
<section class="booking" id="contact"><div class="booking-background">${image('pool-evening','full-image')}</div><div class="booking-content"><p class="eyebrow">YOUR NEXT CHAPTER, IN BALI</p><h2>Your Canggu escape<br><em>starts here.</em></h2>${book()}<div class="direct-benefits"><span>NO PRE-PAYMENT</span><span>FLEXIBLE CANCELLATION</span><span>PAY UPON ARRIVAL</span></div><p class="booking-small">Direct-booking benefits as advertised on Bajalo’s website.<br>Confirm the current terms with the hotel before reserving.</p></div></section>
</main>
<footer><div class="footer-intro"><p>Make yourself<br><em>at home.</em></p><div><span class="eyebrow">LET’S PLAN YOUR STAY</span><a href="mailto:bajalocanggu@gmail.com">bajalocanggu@gmail.com ${arrow}</a><a href="https://wa.me/6287862196293" target="_blank" rel="noopener noreferrer">WhatsApp +62 878 6219 6293 ${arrow}</a></div></div><div class="footer-nav"><span>CANGGU, BALI · ADULTS ONLY</span><nav aria-label="Footer navigation"><a href="#home">Home</a><a href="#cottages">Cottages</a><a href="#gallery">Gallery</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a href="https://www.instagram.com/bajalocottagecanggu/" target="_blank" rel="noopener noreferrer">Instagram ${arrow}</a></div><div class="footer-wordmark">BAJALO</div><div class="footer-bottom"><span>Unofficial redesign concept.</span><span>BAJALO COTTAGE CANGGU · A PRIVATE PROPOSAL</span><a href="#home">BACK TO TOP ↑</a></div></footer>
<dialog id="cottage-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Close dialog">×</button><div class="dialog-photo">${image('cottage')}</div><div class="dialog-content"><p class="eyebrow">BAJALO / THE COTTAGES</p><h2 id="dialog-title">Your own<br><em>little hideaway.</em></h2><p id="dialog-copy">Bajalo has 14 wooden cottages. Each includes a comfortable bed, working desk, mini fridge, air conditioning, a terrace with a chair and table, and an open-air bathroom with a bathtub. Bajalo is an adults-only property.</p>${book()}</div></dialog>
<dialog id="photo-dialog" aria-label="Bajalo photo gallery"><button class="dialog-close" aria-label="Close photograph">×</button><button class="photo-previous" aria-label="Previous photograph">←</button><div class="lightbox-image"></div><button class="photo-next" aria-label="Next photograph">→</button><p class="lightbox-caption"></p></dialog>`;

const routes = [['/','Home'],['/cottages','Cottages'],['/gallery','Gallery'],['/about','About'],['/experience','Experience'],['/contact','Contact']];
const offline = Boolean(window.__BAJALO_OFFLINE__);
const siteBase=window.__BAJALO_BASE__||'';
const routeHref = path => offline ? '#'+path : siteBase+path;
const source = document.createElement('template'); source.innerHTML = homeMarkup;
const section = id => source.content.querySelector('#'+id).outerHTML;
const header = () => {const el=source.content.querySelector('header').cloneNode(true);el.querySelector('nav').innerHTML=routes.map(([path,name])=>`<a href="${routeHref(path)}" ${path===currentRoute()?'aria-current="page"':''}>${name}</a>`).join('');el.querySelector('.crest').href=routeHref('/');return el.outerHTML;};
const footer = () => {const el=source.content.querySelector('footer').cloneNode(true);el.querySelector('nav').innerHTML=routes.map(([path,name])=>`<a href="${routeHref(path)}">${name}</a>`).join('');el.querySelectorAll('a[href="#home"]').forEach(a=>a.href=routeHref('/'));return el.outerHTML;};
const pageIntro=(label,title,copy)=>`<section class="page-intro"><p class="eyebrow">BAJALO COTTAGE CANGGU / ${label}</p><h1>${title}</h1><p class="page-lead">${copy}</p></section>`;
const aboutPage = () => `${pageIntro('ABOUT','A little closer<br>to <em>nature.</em>','Fourteen wooden cottages. A tropical setting. A place to slow down in Canggu, Bali.')}<section class="about-image">${image('garden-path','full-image',true)}<span>OUR OWN CORNER OF CANGGU.</span></section><section class="about-story"><p class="eyebrow">A STAY AT BAJALO</p><div class="story-grid"><h2>Wood, light,<br>and <em>comfort.</em></h2><div><p>BAJALO COTTAGE CANGGU is a place to stay if you are looking for a getaway in Canggu. Our fourteen wooden cottages offer their own space to rest, work or simply unwind.</p><p>Each cottage features an open-air bathroom with a bathtub, a comfortable bed, working desk, mini fridge, air conditioning and a terrace with a chair and table.</p><p>Comfort, service and hospitality are at the heart of Bajalo’s welcome. The property welcomes adults only.</p><a class="underlined" href="${routeHref('/cottages')}">DISCOVER THE COTTAGES ${arrow}</a></div></div></section><section class="about-pair"><div>${image('door-detail')}<p>THE CHARACTER OF WOOD.</p></div><div>${image('cottage')}<p>A COTTAGE OF YOUR OWN.</p></div></section>${section('location')}`;
const galleryPage = () => `${pageIntro('GALLERY','Bajalo,<br><em>in pictures.</em>','The cottages, the pool, the gardens and the little details. All photographs come from Bajalo’s own website.')}<section class="gallery-filters" aria-label="Photo categories"><button data-filter="all" aria-pressed="true">All photographs</button><button data-filter="cottages" aria-pressed="false">The cottages</button><button data-filter="pool" aria-pressed="false">Pool & gardens</button><button data-filter="details" aria-pressed="false">The details</button></section><section class="dedicated-gallery">${Object.keys(pictures).map((file,i)=>{const category=['bedroom','cottage','cottage-interior'].includes(file)?'cottages':['outdoor-bath','bathroom','door-detail'].includes(file)?'details':'pool';return `<figure data-category="${category}"><button data-photo="${file}" aria-label="Enlarge ${pictures[file].toLowerCase()}">${image(file,'',i<2)}</button><figcaption><span>${String(i+1).padStart(2,'0')} / BAJALO</span><span>${category==='cottages'?'THE COTTAGES':category==='details'?'THE DETAILS':'POOL & GARDENS'}</span></figcaption></figure>`;}).join('')}</section>`;
const cottagePage = () => `${pageIntro('COTTAGES','Your own<br><em>little hideaway.</em>','Fourteen wooden cottages for an adults-only stay in Canggu.')}<section class="cottage-cover">${image('bedroom','full-image',true)}</section>${section('cottages')}<section class="room-details"><div><p class="eyebrow">IN EVERY COTTAGE</p><h2>Simple comforts.<br><em>Thoughtful details.</em></h2></div><ul><li>Comfortable bed</li><li>Air conditioning</li><li>Working desk</li><li>Mini fridge</li><li>Terrace with chair and table</li><li>Open-air bathroom with bathtub</li></ul></section><section class="bath-feature">${image('outdoor-bath')}<div><p class="eyebrow">OPEN-AIR BATHING</p><h2>A moment<br>to <em>unwind.</em></h2><p>An open-air bathroom with a bathtub is part of every cottage. A distinctive detail of a stay at Bajalo.</p>${book('outline')}</div></section>`;
const experiencePage = () => `${pageIntro('EXPERIENCE','A slower<br>kind of <em>day.</em>','Wooden cottages, tropical gardens and moments by the water. Discover the atmosphere of Bajalo.')} ${section('experience')}${section('pool')}${section('location')}<section class="experience-inquiry"><h2>Make it<br><em>your stay.</em></h2><p>Have a particular request for your time in Canggu? Speak directly with Bajalo to find out what can be arranged.</p><a class="underlined" href="${routeHref('/contact')}">GET IN TOUCH ${arrow}</a></section>`;
const contactPage = () => `${pageIntro('CONTACT','Let’s plan<br>your <em>escape.</em>','Contact Bajalo directly for availability, current rates and any questions about your stay.')}<section class="contact-grid"><div class="contact-photo">${image('pool-evening','',true)}</div><div class="contact-details"><p class="eyebrow">BAJALO COTTAGE CANGGU</p><h2>Get in<br><em>touch.</em></h2><a href="mailto:bajalocanggu@gmail.com"><small>EMAIL</small><span>bajalocanggu@gmail.com ${arrow}</span></a><a href="https://wa.me/6287862196293" target="_blank" rel="noopener noreferrer"><small>WHATSAPP</small><span>+62 878 6219 6293 ${arrow}</span></a><a href="https://www.instagram.com/bajalocottagecanggu/" target="_blank" rel="noopener noreferrer"><small>INSTAGRAM</small><span>@bajalocottagecanggu ${arrow}</span></a><div class="contact-booking"><p>Canggu, Bali · Adults-only property</p>${book('outline')}</div></div></section><section class="contact-form-section"><div><p class="eyebrow">A NOTE TO BAJALO</p><h2>Tell us about<br><em>your stay.</em></h2><p>This form is a demonstration for the private proposal. It does not send a message. For a reply from the hotel, use email or WhatsApp above.</p></div><form id="contact-form"><label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Email address<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>Your message<textarea name="message" rows="5" required maxlength="2000"></textarea></label><button class="pill outline" type="submit">PREVIEW YOUR REQUEST ${arrow}</button><p id="form-status" role="status" tabindex="-1"></p></form></section><section class="direct-booking-info"><h2>Book <em>direct.</em></h2><p>Bajalo’s website offers direct bookings with no pre-payment, flexible cancellation and payment upon arrival. Confirm the latest rates and conditions with the hotel when reserving.</p><a class="underlined" href="${booking}" target="_blank" rel="noopener noreferrer">CHECK AVAILABILITY ${arrow}</a></section>`;
function homePage(){const main=source.content.querySelector('main').cloneNode(true);main.querySelector('#gallery').outerHTML=`<section class="gallery-teaser"><div><p class="eyebrow">A CLOSER LOOK</p><h2>Bajalo,<br><em>in pictures.</em></h2><a class="underlined" href="${routeHref('/gallery')}">EXPLORE THE GALLERY ${arrow}</a></div><a href="${routeHref('/gallery')}" aria-label="Explore the gallery">${image('garden-path')}</a></section>`;main.querySelector('#experience').outerHTML=`<section class="home-experience"><div>${image('pool-garden')}</div><div><p class="eyebrow">THE BAJALO EXPERIENCE</p><h2>A slower<br>kind of <em>day.</em></h2><p>Tropical gardens, outdoor spaces and time by the water. Discover the atmosphere of Bajalo.</p><a class="underlined" href="${routeHref('/experience')}">DISCOVER THE EXPERIENCE ${arrow}</a></div></section>`;main.querySelector('#pool').remove();main.querySelector('#location').outerHTML=`<section class="home-location"><p class="eyebrow">CANGGU, BALI</p><h2>Your corner<br>of <em>the island.</em></h2><p>The centre and beach are a five-minute scooter ride away, according to Bajalo’s website. Travel time varies with conditions.</p><a class="underlined" href="${routeHref('/about')}">DISCOVER BAJALO ${arrow}</a></section>`;main.querySelector('.stay-description').innerHTML=`<p>Wooden cottages, a terrace of your own and an open-air bathroom with a bathtub. A little space to settle into Canggu.</p><a class="pill outline" href="${routeHref('/cottages')}">DISCOVER OUR COTTAGES ${arrow}</a>`;main.querySelector('.intro-copy .underlined').href=routeHref('/about');main.querySelector('.intro-copy .underlined').innerHTML='OUR STORY '+arrow;return main.innerHTML;}
function currentRoute(){const path=offline?(location.hash.slice(1)||'/'):location.pathname.slice(siteBase.length);return path.replace(/\/$/,'')||'/';}
function render(){const path=currentRoute();const contents={'/':homePage,'/about':aboutPage,'/cottages':cottagePage,'/gallery':galleryPage,'/experience':experiencePage,'/contact':contactPage};const content=contents[path];const dialogs=[...source.content.querySelectorAll('dialog')].map(d=>d.outerHTML).join('');document.querySelector('#app').innerHTML=header()+`<main>${content?content():pageIntro('PAGE NOT FOUND','A little<br><em>detour.</em>',`Return to <a href="${routeHref('/')}">Bajalo’s home page</a>.`)}${path!=='/'&&content?section('contact'):''}</main>`+footer()+dialogs;
 document.body.classList.toggle('inner-page',path!=='/');document.title=`${routes.find(r=>r[0]===path)?.[1]||'Page not found'} — Bajalo Cottage Canggu · Private concept`;
 document.querySelectorAll('main a[href^="#"]').forEach(a=>{const destination={'#cottages':'/cottages','#gallery':'/gallery','#experience':'/experience','#contact':'/contact','#home':'/'}[a.getAttribute('href')];if(destination)a.setAttribute('href',routeHref(destination));});bindInteractions();}
function bindInteractions(){
 const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);document.querySelector('header').classList.toggle('menu-open',open);});
 const cottageDialog=document.querySelector('#cottage-dialog');document.querySelectorAll('[data-cottage]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.dialog-photo').innerHTML=image(['cottage','bedroom','outdoor-bath'][Number(b.dataset.cottage)],'',true);cottageDialog.showModal();}));
 const photoDialog=document.querySelector('#photo-dialog');let currentPhoto=0,items=[];
 function showPhoto(index){items=[...document.querySelectorAll('[data-photo]')].filter(e=>!e.closest('[hidden]'));currentPhoto=(index+items.length)%items.length;const file=items[currentPhoto].dataset.photo;document.querySelector('.lightbox-image').innerHTML=image(file,'',true);document.querySelector('.lightbox-caption').textContent=`${String(currentPhoto+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')} — ${pictures[file]}`;}
 document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{const visible=[...document.querySelectorAll('[data-photo]')].filter(e=>!e.closest('[hidden]'));showPhoto(visible.indexOf(b));photoDialog.showModal();}));document.querySelector('.photo-previous').addEventListener('click',()=>showPhoto(currentPhoto-1));document.querySelector('.photo-next').addEventListener('click',()=>showPhoto(currentPhoto+1));photoDialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showPhoto(currentPhoto+1);}if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(currentPhoto-1);}});
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-category]').forEach(f=>f.hidden=b.dataset.filter!=='all'&&b.dataset.filter!==f.dataset.category);}));
 const form=document.querySelector('#contact-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const status=document.querySelector('#form-status');status.textContent='Demonstration only: your message has not been sent. Please contact Bajalo by email or WhatsApp for a reply.';status.focus();});
 document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
 if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');o.unobserve(e.target);}}),{threshold:.06});document.querySelectorAll('.intro-grid,.section-heading,.stay-card,.amenity-cards article,.pool-heading,.location-grid,.story-grid,.bath-feature,.contact-grid').forEach(e=>{e.classList.add('reveal');o.observe(e);});}
}
render();if(offline)window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
